[2025-04-17T16:03:03.420+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T16:03:03.426+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_Python_pipeline_using_variable.read_and_processing.read_csv_task manual__2025-04-17T13:03:00.454850+00:00 [queued]>
[2025-04-17T16:03:03.432+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_Python_pipeline_using_variable.read_and_processing.read_csv_task manual__2025-04-17T13:03:00.454850+00:00 [queued]>
[2025-04-17T16:03:03.432+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-17T16:03:03.448+0300] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): read_and_processing.read_csv_task> on 2025-04-17 13:03:00.454850+00:00
[2025-04-17T16:03:03.453+0300] {standard_task_runner.py:72} INFO - Started process 391308 to run task
[2025-04-17T16:03:03.465+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_Python_pipeline_using_variable', 'read_and_processing.read_csv_task', 'manual__2025-04-17T13:03:00.454850+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/execute_branching_using_variable.py', '--cfg-path', '/tmp/tmp2tpsedp4']
[2025-04-17T16:03:03.470+0300] {standard_task_runner.py:105} INFO - Job 231: Subtask read_and_processing.read_csv_task
[2025-04-17T16:03:03.608+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_Python_pipeline_using_variable.read_and_processing.read_csv_task manual__2025-04-17T13:03:00.454850+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-17T16:03:03.819+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_Python_pipeline_using_variable' AIRFLOW_CTX_TASK_ID='read_and_processing.read_csv_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T13:03:00.454850+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T13:03:00.454850+00:00'
[2025-04-17T16:03:03.820+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-17T16:03:03.882+0300] {logging_mixin.py:190} INFO -        age     sex    bmi  children smoker     region     charges
0     19.0  female  27.90       0.0    yes  southwest  16884.9240
1     18.0    male  33.77       1.0     no  southeast   1725.5523
2     28.0    male  33.00       3.0     no  southeast   4449.4620
3      NaN     NaN    NaN       NaN    NaN        NaN         NaN
4     25.0    male  28.60       1.0     no  southeast   3366.6697
...    ...     ...    ...       ...    ...        ...         ...
1344  18.0  female  31.92       0.0     no  northeast   2205.9808
1345  18.0  female  36.85       0.0     no  southeast   1629.8335
1346  21.0  female  25.80       0.0     no  southwest   2007.9450
1347   NaN     NaN    NaN       NaN    NaN        NaN         NaN
1348  42.0    male  35.12       0.0     no  southwest   5976.8311

[1349 rows x 7 columns]
[2025-04-17T16:03:03.884+0300] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/airflow/dags/execute_branching_using_variable.py", line 29, in read_csv_file
    ti.xcom_push(key='read_csv', value=df.to_json())
NameError: name 'ti' is not defined
[2025-04-17T16:03:03.894+0300] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=executing_Python_pipeline_using_variable, task_id=read_and_processing.read_csv_task, run_id=manual__2025-04-17T13:03:00.454850+00:00, execution_date=20250417T130300, start_date=20250417T130303, end_date=20250417T130303
[2025-04-17T16:03:03.928+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-17T16:03:03.929+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 231 for task read_and_processing.read_csv_task (name 'ti' is not defined; 391308)
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/airflow/dags/execute_branching_using_variable.py", line 29, in read_csv_file
    ti.xcom_push(key='read_csv', value=df.to_json())
NameError: name 'ti' is not defined
[2025-04-17T16:03:03.971+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-17T16:03:03.995+0300] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T16:03:04.004+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
