[2025-04-15T16:05:16.835+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T16:05:16.844+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_multiple_tasks.task_c scheduled__2025-04-14T00:00:00+00:00 [queued]>
[2025-04-15T16:05:16.848+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_multiple_tasks.task_c scheduled__2025-04-14T00:00:00+00:00 [queued]>
[2025-04-15T16:05:16.848+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-15T16:05:16.861+0300] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_c> on 2025-04-14 00:00:00+00:00
[2025-04-15T16:05:16.863+0300] {standard_task_runner.py:72} INFO - Started process 829 to run task
[2025-04-15T16:05:16.866+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_multiple_tasks', 'task_c', 'scheduled__2025-04-14T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/execute_multiple_tasks.py', '--cfg-path', '/tmp/tmpwf2do4gh']
[2025-04-15T16:05:16.867+0300] {standard_task_runner.py:105} INFO - Job 71: Subtask task_c
[2025-04-15T16:05:16.889+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_multiple_tasks.task_c scheduled__2025-04-14T00:00:00+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-15T16:05:16.926+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_multiple_tasks' AIRFLOW_CTX_TASK_ID='task_c' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-14T00:00:00+00:00'
[2025-04-15T16:05:16.926+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T16:05:16.936+0300] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-15T16:05:16.936+0300] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', 'tmpdfupg52t.sh']
[2025-04-15T16:05:16.939+0300] {subprocess.py:99} INFO - Output:
[2025-04-15T16:05:16.940+0300] {subprocess.py:106} INFO - Task C has Started!
[2025-04-15T16:05:21.943+0300] {subprocess.py:110} INFO - Command exited with return code 130
[2025-04-15T16:05:21.952+0300] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2025-04-15T16:05:21.957+0300] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=executing_multiple_tasks, task_id=task_c, run_id=scheduled__2025-04-14T00:00:00+00:00, execution_date=20250414T000000, start_date=20250415T130516, end_date=20250415T130521
[2025-04-15T16:05:21.974+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-15T16:05:21.974+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 71 for task task_c (Bash command failed. The command returned a non-zero exit code 130.; 829)
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2025-04-15T16:05:22.002+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-15T16:05:22.014+0300] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T16:05:22.020+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
