[2025-04-16T13:31:13.988+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T13:31:14.001+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sqlite_pipeline.update_data manual__2025-04-16T10:31:03.439454+00:00 [queued]>
[2025-04-16T13:31:14.006+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sqlite_pipeline.update_data manual__2025-04-16T10:31:03.439454+00:00 [queued]>
[2025-04-16T13:31:14.007+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-16T13:31:14.019+0300] {taskinstance.py:2890} INFO - Executing <Task(SqliteOperator): update_data> on 2025-04-16 10:31:03.439454+00:00
[2025-04-16T13:31:14.020+0300] {standard_task_runner.py:72} INFO - Started process 97054 to run task
[2025-04-16T13:31:14.025+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sqlite_pipeline', 'update_data', 'manual__2025-04-16T10:31:03.439454+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/sql_operators.py', '--cfg-path', '/tmp/tmplsaeghyv']
[2025-04-16T13:31:14.026+0300] {standard_task_runner.py:105} INFO - Job 120: Subtask update_data
[2025-04-16T13:31:14.054+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_sqlite_pipeline.update_data manual__2025-04-16T10:31:03.439454+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-16T13:31:14.119+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_sqlite_pipeline' AIRFLOW_CTX_TASK_ID='update_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T10:31:03.439454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T10:31:03.439454+00:00'
[2025-04-16T13:31:14.120+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-16T13:31:14.132+0300] {sql.py:266} INFO - Executing: update users set city = 'Cairo';
[2025-04-16T13:31:14.136+0300] {base.py:84} INFO - Retrieving connection 'my_sqlite_conn'
[2025-04-16T13:31:14.153+0300] {base.py:84} INFO - Retrieving connection 'my_sqlite_conn'
[2025-04-16T13:31:14.154+0300] {sql.py:542} INFO - Running statement: update users set city = 'Cairo';, parameters: None
[2025-04-16T13:31:14.155+0300] {sql.py:551} INFO - Rows affected: 9
[2025-04-16T13:31:14.162+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-16T13:31:14.162+0300] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=executing_sqlite_pipeline, task_id=update_data, run_id=manual__2025-04-16T10:31:03.439454+00:00, execution_date=20250416T103103, start_date=20250416T103114, end_date=20250416T103114
[2025-04-16T13:31:14.199+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T13:31:14.217+0300] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-16T13:31:14.225+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
